# Generated by Django 5.0.7 on 2024-08-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('mobileno', models.CharField(max_length=20)),
                ('whatsapp', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('dob', models.DateField()),
                ('blood', models.CharField(max_length=10)),
                ('qualification', models.CharField(choices=[('sslc', 'SSLC'), ('hsc', 'HSC'), ('diploma', 'Diploma'), ('ug', 'UG'), ('pg', 'PG')], default=None, max_length=50, null=True)),
                ('stream', models.CharField(blank=True, max_length=50)),
                ('course', models.CharField(choices=[(6000, 'Microsoft'), (8000, 'Tally'), (10000, 'Programming')], default=None, max_length=20, null=True)),
                ('scheme', models.CharField(choices=[(10, 'General'), (40, 'Referal'), (80, 'walking')], default=None, max_length=10, null=True)),
                ('parentmob', models.CharField(max_length=10)),
                ('regno', models.CharField(max_length=20)),
                ('joindate', models.DateField()),
            ],
        ),
    ]
