# Generated by Django 5.0.7 on 2024-08-09 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enquiry',
            new_name='EnquiryModel',
        ),
    ]
