# Generated by Django 5.0.7 on 2024-08-09 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_enquiry_enquirymodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnquiryModel',
            new_name='Enquiry',
        ),
    ]
